# 错误

## 概念

`Go`语言没有提供像`Java`、`C#`语言中的`try...catch`异常处理方式，而是通过函数返回值逐层往上抛

错误指的是可能出现问题的地方出现了问题。比如打开一个文件时失败，这种情况在人们的意料之中 。

而异常指的是不应该出现问题的地方出现了问题。比如引用了空指针，这种情况在人们的意料之外。可见，错误是业务过程的一部分，而异常不是 。

Go中的错误也是一种类型。错误用内置的`error` 类型表示。就像其他类型的，如int，float64，。错误值可以存储在变量中，从函数中返回，等等。

## 错误类型表示

Go 语言通过内置的错误接口提供了非常简单的错误处理机制

```go
type error interface {
    Error() string
}
```

它包含一个带有Error（）字符串的方法。任何实现这个接口的类型都可以作为一个错误使用。这个方法提供了对错误的描述。

当打印错误时，fmt.Println函数在内部调用Error() 方法来获取错误的描述。这就是错误描述是如何在一行中打印出来的。

### 从错误中提取更多信息的不同方法

- 断言底层结构类型并从结构字段获取更多信息

  ```go
  f, err := os.Open("/test.txt")
  if err, ok := err.(*os.PathError); ok {
      fmt.Println("File at path", err.Path, "failed to open")
      return
  }
  fmt.Println(f.Name(), "opened successfully")
  ```

  

- 断言底层结构类型并使用方法获取更多信息

  ```go
  addr, err := net.LookupHost("golangbot123.com")
  if err, ok := err.(*net.DNSError); ok {
      if err.Timeout() {
          fmt.Println("operation timed out")
      } else if err.Temporary() {
          fmt.Println("temporary error")
      } else {
          fmt.Println("generic error: ", err)
      }
      return
  }
  fmt.Println(addr)
  ```

- 直接比较

  ```go
  func main() {  
      files, error := filepath.Glob("[")
      if error != nil && error == filepath.ErrBadPattern {
          fmt.Println(error)
          return
      }
      fmt.Println("matched files", files)
  }
  ```

  ## 自定义错误

  创建自定义错误可以使用errors包下的New()函数，以及fmt包下的：Errorf()函数。

  ```go
  //errors包：
  func New(text string) error {}
  
  //fmt包：
  func Errorf(format string, a ...interface{}) error {}
  ```

  示例

  ```go
  func circleArea(radius float64) (float64, error) {  
      if radius < 0 {
          return 0, fmt.Errorf("Area calculation failed, radius %0.2f is less than zero", radius)
      }
      return math.Pi * radius * radius, nil
  }
  
  func main() {  
      radius := -20.0
      area, err := circleArea(radius)
      if err != nil {
          fmt.Println(err)
          return
      }
      fmt.Printf("Area of circle %0.2f", area)
  }
  
  func circleArea(radius float64) (float64, error) {  
      if radius < 0 {
          return 0, errors.New("Area calculation failed, radius is less than zero")
      }
      return math.Pi * radius * radius, nil
  }
  
  func main() {  
      radius := -20.0
      area, err := circleArea(radius)
      if err != nil {
          fmt.Println(err)
          return
      }
      fmt.Printf("Area of circle %0.2f", area)
  ```

  更多错误信息

  ```go
  func main() {
  	radius := -3.0
  	area, err :=circleArea(radius)
  	if err != nil {
  		fmt.Println(err)
  		if err, ok := err.(*areaError); ok{
  			fmt.Printf("半径是：%.2f", err.radius)
  		}
  	}
  	fmt.Println(area)
  
  }
  
  type areaError struct {
  	msg    string
  	radius float64
  }
  
  func (e *areaError) Error() string {
  	return fmt.Sprintf("error: 半径， %.2f, %s", e.radius, e.msg)
  }
  
  func circleArea(radius float64) (float64, error) {
  	if radius < 0 {
  		return 0, &areaError{msg: "radius", radius: radius}
  	}
  	return math.Pi * radius * radius, nil
  }
  /*
  error: 半径， -3.00, radius
  半径是：-3.000
  */
  ```

  ## panic 和 recover

  Golang中引入两个内置函数panic和recover来触发和终止异常处理流程，同时引入关键字defer来延迟执行defer后面的函数。 一直等到包含defer语句的函数执行完毕时，延迟函数（defer后的函数）才会被执行，而不管包含defer语句的函数是通过return的正常结束，还是由于panic导致的异常结束。你可以在一个函数中执行多条defer语句，它们的执行顺序与声明顺序相反。 当程序运行时，如果遇到引用空指针、下标越界或显式调用panic函数等情况，则先触发panic函数的执行，然后调用延迟函数。调用者继续传递panic，因此该过程一直在调用栈中重复发生：函数停止执行，调用延迟执行函数等。如果一路在延迟函数中没有recover函数的调用，则会到达该协程的起点，该协程结束，然后终止其他所有协程，包括主协程（类似于C语言中的主线程，该协程ID为1）。

  panic： 1、内建函数 2、假如函数F中书写了panic语句，会终止其后要执行的代码，在panic所在函数F内如果存在要执行的defer函数列表，按照defer的逆序执行 3、返回函数F的调用者G，在G中，调用函数F语句之后的代码不会执行，假如函数G中存在要执行的defer函数列表，按照defer的逆序执行，这里的defer 有点类似 try-catch-finally 中的 finally 4、直到goroutine整个退出，并报告错误

  recover： 1、内建函数 2、用来控制一个goroutine的panicking行为，捕获panic，从而影响应用的行为 3、一般的调用建议 a). 在defer函数中，通过recever来终止一个gojroutine的panicking过程，从而恢复正常代码的执行 b). 可以获取通过panic传递的error

  简单来讲：go中可以抛出一个panic的异常，然后在defer中通过recover捕获这个异常，然后正常处理

  Golang错误和异常是可以互相转换的：

  1. 错误转异常，比如程序逻辑上尝试请求某个URL，最多尝试三次，尝试三次的过程中请求失败是错误，尝试完第三次还不成功的话，失败就被提升为异常了。
  2. 异常转错误，比如panic触发的异常被recover恢复后，将返回值中error类型的变量进行赋值，以便上层函数继续走错误处理流程。

  **什么情况下用错误表达，什么情况下用异常表达，就得有一套规则，否则很容易出现一切皆错误或一切皆异常的情况。**

  以下给出异常处理的作用域（场景）：

  1. 空指针引用
  2. 下标越界
  3. 除数为0
  4. 不应该出现的分支，比如default
  5. 输入不应该引起函数错误

  其他场景我们使用错误处理，这使得我们的函数接口

